#!/usr/bin/env python3
"""Data Structures and Algorithms for CL III, Project 1
See <https://dsacl3-2022.github.io/p1/> for detailed instructions.

Course:      Data Structures and Algorithms for Computational Linguistics 3 WS22/23
Author:      Yin-Yin Cheng (2-person course team; shared implementation)
Honor Code:  I pledge that this program represents my own work.
I received help from: no one in designing and debugging my program.
"""

from fsa import build_trie
from fst import FST
import numpy as np
import json


def build_editfst(alphabet, counts):
    """Build a weighted FST instance that implements one-edit-distance operations.

    You should use the add_transition() method of the FST class
    to build an FST that returns all misspellings of a word
    with one-edit-distance away.

    The transition weight should be set based on the number of times
    particular edit operations were observed in the data (e.g.,
    spelling-data.txt). You are recommended to estimate (smoothed)
    probabilities for each edit operation, and use its logarithm.
    You are free to experiment with weighting schemes, but remember
    that the transduce() method of FST assumes additive weights.

    Arguments:
    ----
    alphabet    All letters that we should recognize
    counts      Counts generated by compute-weights.py
    """

    # The FST should have two states: 0 for the start state, and 1
    # for the final state.
    fst = FST()

    # identity transitions get an inflated weight to bias toward no-edit paths

    m_val = max([w for _, err in counts.items() for _, w in err.items()]) * 20

    for ch in alphabet:
        # Add transitions for the start state
        if (res := counts[ch].get(ch, None)) is not None:
            fst.add_transition(0, ch, 0, ch, np.log(m_val))

        # Add transitions for the final state
        if (res := counts[ch].get(ch, None)) is not None:
            fst.add_transition(1, ch, 1, ch, np.log(m_val))

        # Add transitions for the insertions
        if (res := counts[""].get(ch, None)) is not None:
            fst.add_transition(0, "", 1, ch, np.log(res))

        # Add transitions for the deletions
        if (res := counts[ch].get("", None)) is not None:
            fst.add_transition(0, ch, 1, "", np.log(res))

        # Add transitions for the substitutions
        for ch2 in alphabet:
            if ch != ch2:
                if (res := counts[ch].get(ch2, None)) is not None:
                    fst.add_transition(0, ch, 1, ch2, np.log(res))

    fst.mark_accepting(1)

    return fst


if __name__ == "__main__":
    # Example usage
    with open("lexicon.txt", "rt") as f:
        words = f.read().strip().split()
    with open("spell-errors.json", "rt") as f:
        errcount = json.loads(f.read())
    # Build the trie lexicon
    fsa = build_trie(words)
    # Minimize it (takes about 4 minutes)
    fsa.minimize()
    # Convert it to an FST
    lexicon = FST.fromfsa(fsa)
    # Build the edit-distance FST
    letters = fsa._alphabet
    edits = build_editfst(letters, errcount)
    # Compose them
    spellfst = FST.compose_fst(lexicon, edits)
    # Invert it
    spellfst.invert()
    tdeds = []
    # get unique tranduced string 5 times and concatenate them, sort them by weight
    for tded in spellfst.transduce("wort"):
        s = "".join([t[0] for t in tded])
        w = sum([t[1] for t in tded])

        tdeds.append((s, w))

    tdeds = sorted(tdeds, key=lambda x: x[1], reverse=True)

    from pprint import pprint

    pprint(tdeds)

    for word, weight in tdeds:
        for w in lexicon.transduce(word):
            s = "".join([t[0] for t in w])
            print(s)
